name: Build Image

on:
  schedule:
    - cron: "0 0 */14 * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push base only
        uses: docker/build-push-action@v3
        with:
          push: true
          file: base.Dockerfile
          tags: |
            ${{ github.repository }}:base
            ${{ github.repository }}:latest
